### ISSUE TITLE
Error connecting using Valid Certiticate thumbprint

### ISSUE THREAD

**Issue by dovelus** [soteria-security/365Inspect#101]
**Describe the bug**
Using APPID connection is not correctly working

**To Reproduce**
1. Install powershell 7.4.5
2. Install the modules as described in #99
![image](https://github.com/user-attachments/assets/25ec4ab0-69f1-4275-ba5d-ace8be01d36b)
3. Run .\365Inspect.ps1 -OutPath ..\365_report -UserPrincipalName user@tenant.onmicrosoft.com -Auth APP

**Screenshots**
Full Error
![image](https://github.com/user-attachments/assets/83f59805-dbe6-45e6-9fcf-846fe39b5396)
Certificate in Azure APP
Certificate on azure:
![image](https://github.com/user-attachments/assets/e7f01394-5e80-4f24-8f2a-7c5fa7ba4086)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
To create the app i used this command:
`Register-PnPEntraIDApp -ApplicationName "PnP Rocks" -Tenant [yourtenant].onmicrosoft.com -OutPath c:\mycertificates -DeviceLogin`

**Comment by ThoughtContagion** [comment]
Just to verify, after creating the certificate, you installed the certificate on the machine you're executing the tool from?
You can validate this by using the following command:
```powershell
Get-ChildItem -Path Cert:\ -Recurse | Where-Object { $_.Thumbprint -eq $thumbprint }
```

**Comment by Dovelus** [comment]
I checked the certificates but it seems that the thumbprint is different from my local machine and azure even when i used the same cert

**Comment by Dovelus** [comment]
Ok i rerunned the command by suppling the local thumbprint and now it passed the cert check, 
![image](https://github.com/user-attachments/assets/a9288a25-e89e-489b-9b7e-1aa261b26aea)

**Comment by ThoughtContagion** [comment]
You will also want to ensure that you have granted the appropriate application permissions for all other services to the registered application as outlined in the [Application Authentication Requirements](https://github.com/soteria-security/365Inspect/blob/main/README.md#application-authentication-requirements) in this repos README file.

**Comment by Dovelus** [comment]
I created another self signed certificate but the error still remain the same:
![image](https://github.com/user-attachments/assets/24f7de71-1c7a-4f1d-9826-9a590284a283)
Now the thumb print are the same:
![image](https://github.com/user-attachments/assets/12834bbe-f1b7-48ef-89c8-e08d9dca1000)
![image](https://github.com/user-attachments/assets/00354954-c192-4a0e-8e21-7285fe909e58)

**Comment by ThoughtContagion** [comment]
Are you able to connect to the PnP service using this thumbprint?

```powershell
Connect-PnPOnline -Url "https://[your_org_name]-admin.sharepoint.com" -ClientId $appID -Thumbprint $thumbprint -Tenant [your_tenant_domain]
```
For example:
```powershell
Connect-PnPOnline -Url "https://mycompany-admin.sharepoint.com" -ClientId $appID -Thumbprint $thumbprint -Tenant mycompany.com
```

**Comment by Dovelus** [comment]
Here is the output yep i think her can't find the certificate and just for context the Cert is under APP Registration -> 365 Inspect -> Manage -> Certificates 
![image](https://github.com/user-attachments/assets/9b0712fc-0b1e-4995-aaf6-6d972fbe139c)

**Comment by ThoughtContagion** [comment]
This error appears to be related to your local machine and not the application in Microsoft Entra.

Does this command return any output?
```powershell
Get-ChildItem -Path Cert:\CurrentUser\My | Where-Object { $_.Thumbprint -eq $thumbprint }
```
![image](https://github.com/user-attachments/assets/1ca7f5af-40ea-4e14-b909-0d4a5da85acd)

**Comment by Dovelus** [comment]
This machine is freshly installed windows VM so i exclude any problem related directly to my system
![image](https://github.com/user-attachments/assets/e182d33a-0101-4e08-9b4b-9d6d3cc8cc22)

**Comment by Dovelus** [comment]
Thanks it worked beautifully the Cert problem is solved. As you suggested i configured the permissions as shown in the README, but is seems that even with  Directory.Read.All the command Get-MgOrganization still is not working

**Comment by ThoughtContagion** [comment]
Are the permissions granted using the 'Grant Admin Consent' button?
Your application's permissions should look like this:
![image](https://github.com/user-attachments/assets/b0aa29da-5930-4a7c-9e99-b5a56b9d47bf)
