### ISSUE TITLE
Extra Values in the .html report

### ISSUE THREAD

**Issue by asterictnl-lvdw** [soteria-security/365Inspect#24]
Is there a way to add the following in the report extra:
- Default Value
- Expected Value
- Current Value

I want to add the information in the .json file when necessary to make the report a bit more detailed. 

Let me know if it's possible.

For example the HTML report now has not a value for default value or expected value. 

in the .JSON this is easy added by adding the option and hard-code the text into it when necessary. PowerShell wise I do not know where it could be added.

**Comment by asterictnl-lvdw** [comment]
I think it should be something like this in the PowerShell module:
```
        #Finding Default Value
        ForEach ($DefaultValue in $finding.DefaultValue){
        $short_finding_html = $short_finding_html.Replace("{{DEFAULTVALUE}}", $finding.DefaultValue)
        $long_finding_html = $long_finding_html.Replace("{{DEFAULTVALUE}}", $finding.DefaultValue)
        }

        #Finding Expected Value
        ForEach ($ExpectedValue in $finding.ExpectedValue){
        $short_finding_html = $short_finding_html.Replace("{{EXPECTEDVALUE}}", $finding.ExpectedValue)
        $long_finding_html = $long_finding_html.Replace("{{EXPECTEDVALUE}}", $finding.ExpectedValue)
        }	
```

This could be added in the table as well as in the long findings underneath.

**Comment by ThoughtContagion** [comment]
Thank you. We will look at the value of adding this to the report. It would not be applicable to all inspectors as some findings have no default values, but it may be beneficial in some others.

**Comment by asterictnl-lvdw** [comment]
> Thank you. We will look at the value of adding this to the report. It would not be applicable to all inspectors as some findings have no default values, but it may be beneficial in some others.

Well I have written some scripts based on the CIS benchmark. Most of them do audit and have a default value. As I said the inspectors that do contain a default value and an expected value it is handy to check if the current settings are default or changed and still not correct. That would make an report more powerful.

For inspectors that do not have these values it can be ignored. It is just an addition to the HTML report and to the script so .json files can include the default value so it can be compared with current data. 

I will look forward to if the implementation is applicable.
