### ISSUE TITLE
".\Inspector\Write-ErrorLog.ps1" was not found

### ISSUE THREAD

**Issue by tbecirovic** [soteria-security/365Inspect#27]
Hi all,
first of all thanks a lot for the script which helped me a lot of quickly auditing a tenant.
My onliest error that occurs on 3-4 times during the whole script is the following: The Write-ErrorLog.ps1 Script was not found in the .\Inspector folder -> and that's correct there is no Write-Error Script. The expression in the script who invoke these lines is:
$finding.AffectedObjects = Invoke-Expression ".\inspectors\$selected_inspector.ps1"
It not seems to be correct :)

**Comment by ThoughtContagion** [comment]
Thank you,
I'll fix this.

**Comment by ThoughtContagion** [comment]
Pull Request to resolve created - https://github.com/soteria-security/365Inspect/pull/30
