### ISSUE TITLE
Missing CMDlets

### ISSUE THREAD

**Issue by LiamRomanis-at-RootshellSecurity** [soteria-security/365Inspect#38]
**Describe the bug**
Get-SafeAttachmentPolicy is not longer present in the installed modules. 

**To Reproduce**
1. Install modules listed of github readme
2. run 365inspect.ps1

**Expected behavior**
I expected that the cmdlets would be present. 

**Screenshots**
![Screenshot from 2022-05-12 12-20-20](https://user-images.githubusercontent.com/68328996/168063483-05d5e3a1-78b7-4f91-85c1-49a63d229802.png)

**Desktop (please complete the following information):**
Edition	Windows 10 Pro
Version	21H1
Installed on	‎17/‎02/‎2021
OS build	19043.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Powershell Version**
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Additional context**
I also found that cmdlets such as Get-SafeLinksPolicy and Get-SafeAttachmentPolicy were not found, although 365inspect did seem to manage to find and run them. 

Thanks

**Comment by ThoughtContagion** [comment]
Hi there!
Thank you for using 365Inspect!
These cmdlets all rely on the user running the scripts having the proper permissions, and connecting to the Security and Compliance Center via PowerShell. The script handles these session connections, but cannot determine if the user running them has the correct permissions to run each command - in the case of these particular cmdlets, ATP/Defender licensing and permissions. If you could validate that those licenses and permissions are correct, we can begin to look further into this issue.

I can confirm that the cmdlets are still present in the Exchange PowerShell module version 2.0.5
![image](https://user-images.githubusercontent.com/88730003/168096667-53690f8e-dbac-4598-abc7-4da5d374d16c.png)
![image](https://user-images.githubusercontent.com/88730003/168096971-4a7edbe9-61fe-4b06-b337-d31a957c440b.png)
![image](https://user-images.githubusercontent.com/88730003/168097197-ec4042f5-0916-49d7-9623-f8c8e9299d8d.png)

The cmdlets listed with tmp_* as the source, are imported functions from the Exchange Online module
[Get-SafeLinksPolicy](https://docs.microsoft.com/en-us/powershell/module/exchange/get-safelinkspolicy?view=exchange-ps)
[Get-DlpCompliancePolicy](https://docs.microsoft.com/en-us/powershell/module/exchange/get-dlpcompliancepolicy?view=exchange-ps)

**Comment by ThoughtContagion** [comment]
Your license structure looks correct - both the RIGHTSMANAGEMENT_ADHOC and O365_BUSINESS_PREMIUM licenses should grant you access to these cmdlets if you have the appropriate roles. Due to the use of the two Graph modules and the requirement of admin consent, we recommend Global Admin role (we are actively working towards reducing the required permissions as much as possible), but for those specific cmdlets Security Reader or Global Reader roles should be sufficient to return the results of inspectors. [Security and Compliance Permissions](https://docs.microsoft.com/en-us/microsoft-365/compliance/microsoft-365-compliance-center-permissions?view=o365-worldwide)
If you are able to retrieve the results when running the tool, and hold the appropriate roles, then the error messages are just odd. Unfortunately, we cannot troubleshoot the modules themselves, but we're always happy to try to help as much as possible to get you into a good spot while using our tool!

**Comment by ThoughtContagion** [comment]
Interesting.
What results do you get when you run this?

```
$Username = Read-Host -Prompt "Enter your UserPrincipalName (eg user@mycompany.com or user @mycompany.onmicrosoft.com)"
Connect-ExchangeOnline -UserPrincipalName $Username -ShowBanner:$false
Connect-IPPSSession

$cmdlets = @("Get-DlpCompliancePolicy","Get-DlpSensitiveInformationType","Get-SafeLinksPolicy","Get-SafeAttachmentPolicy")

Foreach ($cmdlet in $cmdlets){
    Try{
        Get-Command $cmdlet
    }
    Catch{
        Write-Warning "$cmdlet not found."
    }
}
```
I would expect something like this (source names will likely be different)
![image](https://user-images.githubusercontent.com/88730003/168128984-5440ed68-2d2b-438e-b77c-470d4fb8932a.png)

**Comment by ThoughtContagion** [comment]
Unfortunately, it looks like reply by email drops the attachments. Could you paste it into the [Issue](https://github.com/soteria-security/365Inspect/issues/38)?

**Comment by LiamRomanis-at-RootshellSecurity** [comment]
![Screenshot from 2022-05-12 18-01-05](https://user-images.githubusercontent.com/68328996/168167433-aaf7c96b-9b0d-454e-a24d-f62c4c1146e9.png)

**Comment by ThoughtContagion** [comment]
Can you try the following?

```
Disconnect-ExchangeOnline 

$Username = Read-Host -Prompt "Enter your UserPrincipalName (eg ***@***.*** or user @mycompany.onmicrosoft.com)"

Connect-ExchangeOnline -UserPrincipalName $Username -ShowBanner:$false

Connect-IPPSSession

Import-Module ExchangeOnlineManagement -Force

$cmdlets = @("Get-DlpCompliancePolicy","Get-DlpSensitiveInformationType","Get-SafeLinksPolicy","Get-SafeAttachmentPolicy")

Foreach ($cmdlet in $cmdlets){
    Try{
        Get-Command $cmdlet
    }
    Catch{
        Write-Warning "$cmdlet not found."
    }
}
```

**Comment by LiamRomanis-at-RootshellSecurity** [comment]
New-ExoPSSession : Processing data from remote server gbr01b.ps.compliance.protection.outlook.com failed with the
following error message: Fail to create a runspace because you have exceeded the maximum number of connections allowed
: 3. Please close existing runspace and try again. For more information, see the about_Remote_Troubleshooting Help
topic.
At C:\Program
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\netFramework\ExchangeOnlineManagement.psm1:475 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-ExoPSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Exchang
   e.Management.ExoPowershellSnapin.NewExoPSSession

**Comment by ThoughtContagion** [comment]
Ok, how about running `Disconnect-ExchangeOnline` by itself, and then the above commands?

**Comment by LiamRomanis-at-RootshellSecurity** [comment]
same error I'm affraid

**Comment by LiamRomanis-at-RootshellSecurity** [comment]
maybe I should uninstall Powershell and start again. Up early tomorrow so got to go to bed, sorry. Thanks for you help so far

**Comment by ThoughtContagion** [comment]
No problem.
You can also try installing the modules system-wide as an admin if you haven't already. The script prompt installs for the current user only.

**Comment by LiamRomanis-at-RootshellSecurity** [comment]
Morning. After re-installing Powershell (rebooting in between) I installed ExchangeOnlineManagement and ran the set of commands you sent over. This was the result:

![Screenshot from 2022-05-13 08-41-48](https://user-images.githubusercontent.com/68328996/168235863-cd6ad93e-f003-4568-a9e6-07272db7448c.png)

**Comment by LiamRomanis-at-RootshellSecurity** [comment]
OK, think I figured it out.. my account has MFA enforced

**Comment by ThoughtContagion** [comment]
That would certainly do it. If your session wasn't authed to the Security and Compliance module you wouldn't see some of those commands.
Thanks for hanging in there!

**Comment by LiamRomanis-at-RootshellSecurity** [comment]
Same error

**Comment by ThoughtContagion** [comment]
Hi there!

This seems like an authentication issue to the Security and Compliance center.
This may be due to a difference in your connection URI. Please see [Microsoft's documentation](https://learn.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps) about the differences in parameters.

![image](https://user-images.githubusercontent.com/88730003/195125906-555f9734-7b93-4b7d-9dea-e55a6b2fd343.png)

**Comment by ThoughtContagion** [comment]
Unable to replicate the issue and no response since October. Will reopen in the future if the issue is not resolved.
