### ISSUE TITLE
Residual Rating

### ISSUE THREAD

**Issue by PaulaSillars** [soteria-security/365Inspect#41]
When running the report this morning against out tenant, the Residual Risk rating column shows {{RISKRATING}}.  I ran it once as Global Reader and then again as a Global Admin with the same result.  

Note this is the first time I have used 365Inspect so apologies if this is an issue at my end.

![riskrating](https://user-images.githubusercontent.com/108845445/177675397-89696fbc-e085-4c30-962c-7c9cb85c7bcb.jpg)

**Comment by ThoughtContagion** [comment]
Thank you, a pull request has been submitted to remediate this issue.
