### ISSUE TITLE
The assignment expression is not valid

### ISSUE THREAD

**Issue by shadysheeds** [soteria-security/365Inspect#45]
`PS C:\Users\User\OneDrive\Documents\365Inspect-main> .\365Inspect.ps1 -OrgName mycompany -OutPath ..\365_report -Auth MFA
At C:\Users\User\OneDrive\Documents\365Inspect-main\365Inspect.ps1:50 char:35
[string[]] $SelectedInspectors = @(),

The assignment expression is not valid. The input to an assignment operator must be an object that is able to accept assignments, such as a variable or a property.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : InvalidLeftHandSide`

**Comment by ThoughtContagion** [comment]
Can you share a screenshot and steps of how you received this error?
If you can provide some system information as well, that would be great.
PowerShell version and OS version.

**Comment by ThoughtContagion** [comment]
PR [46](https://github.com/soteria-security/365Inspect/pull/46#issue-1308552365) may fix this issue.

**Comment by shadysheeds** [comment]
Hi,

Screenshot attached.
![365inspect](https://user-images.githubusercontent.com/87165328/179629634-2e6c89fe-a6fd-4ffc-a35f-c4c531adb855.PNG)


Version info.


Name                           Value                                                                                                                                                                        
----                           -----                                                                                                                                                                        
PSVersion                      5.1.19041.1682                                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                      
BuildVersion                   10.0.19041.1682                                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                          
SerializationVersion           1.1.0.1 

I have tried #46 with same issue.

**Comment by ThoughtContagion** [comment]
We are unable to replicate this issue.

This is the local repo:
![image](https://user-images.githubusercontent.com/88730003/179790512-d9590d69-5856-4c50-a4a7-7060ffe784ad.png)


and this is a direct download from the GitHub repo:
![image](https://user-images.githubusercontent.com/88730003/179798490-8573920c-ff72-4cbe-be56-525d5b66604f.png)

Do you encounter the issue if you run it outside of PowerShell ISE?

**Comment by ThoughtContagion** [comment]
Unable to reproduce the issue in multiple environments
