### ISSUE TITLE
Report HTML contains broken links to txt-files

### ISSUE THREAD

**Issue by mihanf** [soteria-security/365Inspect#63]
**Description**
If Inspector Module Output is too long (more than 25 items) the output is saved into a seperate txt-file with the name [findingname].txt. A Link to this file is then placed in the HTML-Report. If the links are clicked they never work.
This is because there is only the name of the finding into the report. It should be the findingname + "txt".
In the Script 365Inspect.ps1

**Example**
Inspector Module "UsersWithNoMFAConfigured" often generates more than 25 items and the text file can not be accessed via HTML-Report.

**Solution**
Line 472: `$condensed = "<a href='{name}'>{count} Affected Objects Identified<a/>."`
Should be: `$condensed = "<a href='{name}.txt'>{count} Affected Objects Identified<a/>."`

**Comment by ThoughtContagion** [comment]
Fix is incoming for this.
In testing now.
