### ISSUE TITLE
When excuting The term 'Select-MgProfile' is not recognized

### ISSUE THREAD

**Issue by kennyb7322** [soteria-security/365Inspect#70]
When executing 365inspect and the parameters using Powershell 7.3.5 not able to  select MGProfiles as seen below from the output.

Verifying environment.

Environment is 7.3.5
        [+] PowerShellGet is installed.
        Importing PowerShellGet
Environment is 7.3.5
        [+] ExchangeOnlineManagement is installed.
        Inporting ExchangeOnlineManagement
        Importing Microsoft.Graph
Environment is 7.3.5
        [+] Microsoft.Graph is installed.
        Inporting ExchangeOnlineManagement
        Importing Microsoft.Graph
Environment is 7.3.5
        [+] Microsoft.Online.SharePoint.PowerShell is installed.
        Importing Microsoft.Online.SharePoint.PowerShell
Environment is 7.3.5
        [+] MicrosoftTeams is installed.
        Importing MicrosoftTeams
Connecting to Microsoft Graph
Welcome To Microsoft Graph!
Connecting to Microsoft Graph Failed.
**Write-Error: C:\365inspect\365Inspect.ps1:294
**Line |
 294 |          Connect-Services
     |          ~~~~~~~~~~~~~~~~
     | The term 'Select-MgProfile' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
     | again.****
PS C:\365inspect>

It has worked on earlier versions of the 365Inspect but not with the most updated one with some changes and modifications.

**Comment by ThoughtContagion** [comment]
Hi there!
Thank you for checking out our tool!
Please verify that you are able to connect to, and approve permissions for, Microsoft Graph PowerShell.
In your screenshot, your connection to Microsoft Graph failed (the line immediately before the error message about `Select-MgProfile`
![image](https://github.com/soteria-security/365Inspect/assets/88730003/8f083ce8-d707-435b-8a2e-61431fa6462d)

When properly connected, you should see a message that you are connected via Graph to your tenant before connecting to the next module.
![image](https://github.com/soteria-security/365Inspect/assets/88730003/76e71f86-60c0-454e-b004-8949eec06cdf)

**Comment by kennyb7322** [comment]
I agree on the connectivity to Graph when running it direct connect-graph & connect-mggraph It works without failure.

<img width="254" alt="image" src="https://github.com/soteria-security/365Inspect/assets/6541163/bd586125-b5aa-499c-9364-9da3bd0bef7e">

**Comment by ThoughtContagion** [comment]
Could you try running the tool again? 
In our testing, and the screenshot above, we ran it in PS version 7.3.5 and had no issues connecting.

**Comment by kennyb7322** [comment]
Yes, I ran it several times and still received the same error. The service principal I am using is fully capable and has all the access. Not sure why it bombs out on the Microsoft Graph on the new version but the old version works fine.

**Comment by ThoughtContagion** [comment]
Hi @kennyb7322 
The authentication methods used in this tool are designed for an authenticated user, and currently does not support using a Service Principal or Application authentication context.

**Comment by kennyb7322** [comment]
I could get it to work by using an older version of PowerShell, the beta version; I was getting the same results. I don't know if some authentication caused it not to execute properly. I am going to try it on different instances and report back.
<img width="892" alt="image" src="https://github.com/soteria-security/365Inspect/assets/6541163/4439e7f2-b63f-4d75-b1a2-dbd968f9dcf2">

**Comment by ThoughtContagion** [comment]
What version of Microsoft.Graph PowerShell Module do you have installed?
This works currently, using user credentials, with version 1.19.0 and lower.

**Comment by kennyb7322** [comment]
So it works on Powershell 1.9.6      Microsoft.Graph and lower you are correct it does not work in 2.0.0. and it does not work also on the release candidates.

**Comment by kennyb7322** [comment]
So it works on my VM but when I try to push it up to github I get an error. Any help will be greatly appreciated! Thanks.Manifest   1.9.6      Microsoft.Graph

**Comment by ThoughtContagion** [comment]
Version 2.0.0 no longer supports the `Select-MgProfile` command.
In Microsoft's release notes for version 2.0.0 - [https://github.com/microsoftgraph/msgraph-sdk-powershell/releases](https://github.com/microsoftgraph/msgraph-sdk-powershell/releases)
![image](https://github.com/soteria-security/365Inspect/assets/88730003/d27cf605-fddc-42b7-9fcf-76ccefb4d8f9)

We are working on a resolution to accommodate this change, in the meantime, you will need version 1.19.0 or lower to run the tool.
