### ISSUE TITLE
Does this work in M365 GCC High?

### ISSUE THREAD

**Issue by mike16329** [soteria-security/365Inspect#76]
Does this work in M365 GCC High?

**Comment by ThoughtContagion** [comment]
This tool is designed to run in any environment so long as you hold the appropriate permissions. That said, Microsoft does restrict some functionality in GCC High environments to comply with those requirements and we have not had the fortune to test in a GCC High environment yet. We would certainly be interested to know of any issues or your experience in general.

**Comment by mike16329** [comment]
Ok thanks! I know that GCC High uses the login.microsoftonline.us URL instead of login.microsoftonline.com URL, would this cause issues with any of the script(s)?

**Comment by ThoughtContagion** [comment]
This would only affect the wrapper script - 365Inspect.ps1, where authentication calls are sent to Microsoft.
We are pushing a change to the tool shortly and will take it as an action item to include this functionality to choose the Microsoft environment.

**Comment by mike16329** [comment]
Thanks! I know too for GCC High the graph url needs to be graph.microsoft.us not graph.microsoft.com
