### ISSUE TITLE
Output Report.html:  no work in oder device

### ISSUE THREAD

**Issue by Giupy75** [soteria-security/365Inspect#81]
**Describe the bug**
When I export the Report.html file to another Windows computer, the report does not build the Risk Severity and Risk Distribution charts, the rest of the Report.html is compiled correctly. I also exported the entire folder with the zip file, but the final result is the same.

**To Reproduce**
1. Create a report with the PowerShell script, export the report to another device.

**Comment by ThoughtContagion** [comment]
Can you elaborate on how you're exporting the report to another device? Are you using a network path?

**Comment by Giupy75** [comment]
Thank you for your attention. I tried to copy also via USB stick, first only the report.html file, then the entire zip file. When I run the report.html file, the file opens but it does not build the Risk Severity and Risk Distribution part. The rest is all present. I also edited the file, I checked that 
```
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>
```
are reachable, no problem in reaching the sources. I also sent the report.html file via teams to a colleague of mine, the problem persists.

**Comment by ThoughtContagion** [comment]
The charts do not render when you move the file, but they do on the machine you ran the assessment on?

**Comment by Giupy75** [comment]
Correct, on my PC where I did the evaluation, everything works correctly. I did another test, I created the output folder in the OneDrive folder, on the my  PC where I perform the evaluation. The readme.html file opens correctly. Then I moved to another device, I ran the file from inside the OneDrive folder, and the problem still occurs

**Comment by ThoughtContagion** [comment]
We are unable to replicate this issue.
We have saved to OneDrive locations, network shares, direct to USB, and shared/transferred between all of the above.
Do you happen to have any DLP or other security tools/configurations that may strip images from HTML files?

**Comment by Giupy75** [comment]
I thank you very much for the time you have dedicated to me. I solved thanks to your suggestion. DLP was creating problems for me. You were very kind.
