### ISSUE TITLE
Microsoft 365 Assessment can't export the data

### ISSUE THREAD

**Issue by takiguchiyuka** [soteria-security/365Inspect#88]
I ran .\microsoft365-assessment.exe, but it says "Error creating report for this Microsoft 365 Assessment due to error: Assessment "omitted"
"was not Finished or Paused, can't export the data" was displayed. I hope for a solution.

**Comment by ThoughtContagion** [comment]
Hi there,

I'm sorry, but I don't believe you've opened this issue on the correct project. 
This tool is a collection of modular PowerShell scripts and does not contain any .exe files.
