### ISSUE TITLE
Compatibility Issues between Powershell Modules

### ISSUE THREAD

**Issue by mihanf** [soteria-security/365Inspect#95]
I made a fresh install of the necessary Powershell Modules. With the latest Exchange Online Management Module (3.5.0) installed I got an Error when the Script tries "Connect-MgGraph". The Error was like "Dependency not found".
After installing the prior EXO Module 3.4.0 it works as expected.

**Comment by ThoughtContagion** [comment]
Hi there @mihanf, 

Thank you for reporting this issue. Unfortunately, this is an issue with the Microsoft.Identity.Client dependency in both the Exchange PowerShell module and Microsoft Graph PowerShell modules and appears to be a recurring problem with updates to either or both modules.

Previous example:
[Connect-MgGraph Interactive not working if connected at first to Exchange Online PS](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2227)
